name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies & build
        run: |
          npm install
          npm run build

      - name: Prepare VPS folders
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            # Tạo folder chính và build nếu chưa có
            mkdir -p /home/${{ secrets.VPS_USER }}/apps/eng-dictation-web/build
            # Xóa build cũ nếu có
            rm -rf /home/${{ secrets.VPS_USER }}/apps/eng-dictation-web/build/*

      - name: Deploy build to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: "build/*"
          target: "/home/${{ secrets.VPS_USER }}/apps/eng-dictation-web"

      - name: Restart PM2 and serve React app
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /home/${{ secrets.VPS_USER }}/apps/eng-dictation-web
            # Cài serve nếu chưa có
            npm install -g serve
            # Stop app cũ nếu đang chạy
            pm2 stop eng-dictation-web || true
            # Start app React SPA bằng serve, trỏ đúng folder build
            pm2 start npx --name eng-dictation-web -- serve -s /home/${{ secrets.VPS_USER }}/apps/eng-dictation-web/build -l 5173
            # Lưu trạng thái PM2
            pm2 save
