name: toeic_test
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies & build
        run: |
          npm install
          npm run build

      - name: Prepare VPS folders
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ vars.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ vars.VPS_PORT }}
          script: |
            mkdir -p /home/${{ vars.VPS_USER }}/apps/${{ vars.PROJECT_NAME }}/build
            rm -rf /home/${{ vars.VPS_USER }}/apps/${{ vars.PROJECT_NAME }}/build/*

      - name: Deploy build to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ vars.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ vars.VPS_PORT }}
          source: "build/*"
          target: "/home/${{ vars.VPS_USER }}/apps/${{ vars.PROJECT_NAME }}"

      - name: Restart PM2 and serve React app
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ vars.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ vars.VPS_PORT }}
          script: |
            cd /home/${{ vars.VPS_USER }}/apps/${{ vars.PROJECT_NAME }}
            npm install -g serve
            pm2 stop ${{ vars.PROJECT_NAME }} || true
            pm2 start --name ${{ vars.PROJECT_NAME }} -- npx serve -s /home/${{ vars.VPS_USER }}/apps/${{ vars.PROJECT_NAME }}/build -l ${{ vars.PROJECT_PORT }}
            pm2 save
